INSERT INTO states (id, name) VALUES ('SL', 'Saarland');

INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Beckingen', '', '66701','SL');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Bexbach', '', '66450','SL');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Blieskastel', '', '66440','SL');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Bous', '', '66359','SL');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Dillingen', ' Saar', '66763','SL');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Ensdorf', ' Saar', '66806','SL');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Eppelborn', '', '66571','SL');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Freisen', '', '66629','SL');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Friedrichsthal', ' Saar', '66299','SL');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Gersheim', '', '66453','SL');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Großrosseln', '', '66352','SL');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Heusweiler', '', '66265','SL');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Homburg', ' Saar', '66424','SL');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Illingen', ' Saar', '66557','SL');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Kirkel', '', '66459','SL');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Kleinblittersdorf', '', '66271','SL');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Lebach', '', '66822','SL');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Losheim', 'am See', '66679','SL');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Mandelbachtal', '', '66399','SL');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Marpingen', '', '66646','SL');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Merchweiler', '', '66589','SL');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Merzig', '', '66663','SL');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Mettlach', '', '66693','SL');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Nalbach', '', '66809','SL');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Namborn', '', '66640','SL');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Neunkirchen', ' Saar', '66538','SL');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Neunkirchen', ' Saar', '66539','SL');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Neunkirchen', ' Saar', '66540','SL');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Nohfelden', '', '66625','SL');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Nonnweiler', '', '66620','SL');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Oberthal', ' Saar', '66649','SL');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Ottweiler', '', '66564','SL');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Perl', ' Saar', '66706','SL');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Püttlingen', '', '66346','SL');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Quierschied', '', '66287','SL');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Rehlingen-Siersburg', '', '66780','SL');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Riegelsberg', ' Saar', '66292','SL');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Saarbrücken', '', '66111','SL');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Saarbrücken', '', '66113','SL');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Saarbrücken', '', '66115','SL');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Saarbrücken', '', '66117','SL');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Saarbrücken', '', '66119','SL');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Saarbrücken', '', '66121','SL');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Saarbrücken', '', '66123','SL');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Saarbrücken', '', '66125','SL');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Saarbrücken', '', '66126','SL');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Saarbrücken', '', '66127','SL');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Saarbrücken', '', '66128','SL');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Saarbrücken', '', '66129','SL');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Saarbrücken', '', '66130','SL');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Saarbrücken', '', '66131','SL');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Saarbrücken', '', '66132','SL');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Saarbrücken', '', '66133','SL');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Saarlouis', '', '66740','SL');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Saarwellingen', '', '66793','SL');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Schiffweiler', '', '66578','SL');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Schmelz', ' Saar', '66839','SL');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Schwalbach', ' Saar', '66773','SL');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Spiesen-Elversberg', '', '66583','SL');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('St. Ingbert', '', '66386','SL');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('St. Wendel', ' Saar', '66606','SL');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Sulzbach', ' Saar', '66280','SL');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Tholey', '', '66636','SL');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Überherrn', '', '66802','SL');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Völklingen', '', '66333','SL');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Wadern', '', '66687','SL');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Wadgassen', '', '66787','SL');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Wallerfangen', '', '66798','SL');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Weiskirchen', ' Saar', '66709','SL');
