INSERT INTO states (id, name) VALUES ('HE', 'Land Hessen');

INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Aarbergen', '', '65326', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Abtsteinach', '', '69518', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Ahnatal', '', '34292', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Alheim', '', '36211', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Allendorf', '(Eder)', '35108', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Allendorf', '(Lumda)', '35469', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Alsbach-Hähnlein', '', '64665', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Alsfeld', '', '36304', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Altenstadt', ' Hess', '63674', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Am Rainberge', '', '34497', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Am Römerhof', '', '61200', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Am Römerschacht', '', '61200', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Am Rüdesheimer Hafen', ' Rheingau', '65385', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Am Sandkopf', 'Gem Fuldatal', '34127', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Amöneburg', '', '35287', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Angelburg', ' Hess', '35719', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Antrifttal', '', '36326', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Aßlar', '', '35614', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Babenhausen', ' Hess', '64832', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Bad Arolsen', '', '34454', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Bad Camberg', '', '65520', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Bad Emstal', '', '34308', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Bad Endbach', '', '35080', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Bad Hersfeld', '', '36251', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Bad Homburg', 'v d Höhe', '61348', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Bad Homburg', 'v d Höhe', '61350', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Bad Homburg', 'v d Höhe', '61352', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Bad Karlshafen', '', '34385', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Bad König', '', '64732', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Bad Nauheim', '', '61231', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Bad Orb', '', '63619', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Bad Salzschlirf', '', '36364', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Bad Schwalbach', '', '65307', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Bad Soden', 'am Taunus', '65812', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Bad Soden-Salmünster', '', '63628', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Bad Sooden-Allendorf', '', '37242', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Bad Vilbel', '', '61118', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Bad Wildungen', '', '34537', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Bad Zwesten', '', '34596', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Battenberg', '(Eder)', '35088', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Baunatal', '', '34225', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Bebra', '', '36179', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Beerfelden', ' Odenw', '64743', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Bei den Tongruben', '', '63543', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Bellers', ' Hess', '36208', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Bensheim', '', '64625', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Berkatal', '', '37297', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Beselich', '', '65614', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Biblis', '', '68647', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Bickenbach', ' Bergstr', '64404', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Biebergemünd', '', '63599', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Biebertal', ' Hessen', '35444', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Biebesheim', 'am Rhein', '64584', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Biedenkopf', '', '35216', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Bingenheimer Mühle', '', '61203', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Birkenau', ' Odenw', '69488', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Birkenstöcke', ' Gem Birstein', '63699', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Birstein', '', '63633', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Bischoffen', '', '35649', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Bischofsheim', 'b Rüsselsheim', '65474', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Borken', '(Hessen)', '34582', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Brachttal', '', '63636', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Braunfels', '', '35619', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Brechen', '', '65611', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Breidenbach', 'b Biedenkopf', '35236', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Breitenbach', 'a. Herzberg', '36287', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Breitscheid', ' Hess', '35767', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Brensbach', '', '64395', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Breuberg', '', '64747', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Breuna', '', '34479', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Brombachtal', '', '64753', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Bromskirchen', '', '59969', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Bruchköbel', '', '63486', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Büdingen', ' Hess', '63654', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Burghaun', '', '36151', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Burgwald', ' Eder', '35099', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Bürstadt', '', '68642', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Buseck', '', '35418', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Büttelborn', '', '64572', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Butzbach', '', '35510', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Calden', ' Hess', '34379', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Capelle', ' Hof', '35043', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Capelle', ' Hof', '35043', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Cölbe', '', '35091', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Cölbe', '', '35091', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Cornberg', ' Hess', '36219', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Dammeshof', '', '36326', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Dammesmühle', '', '36326', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Darmstadt', '', '64283', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Darmstadt', '', '64285', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Darmstadt', '', '64287', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Darmstadt', '', '64289', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Darmstadt', '', '64291', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Darmstadt', '', '64293', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Darmstadt', '', '64295', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Darmstadt', '', '64297', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Dautphetal', '', '35232', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Dieburg', '', '64807', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Diemelsee', '', '34519', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Diemelstadt', '', '34474', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Dietzenbach', '', '63128', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Dietzhölztal', '', '35716', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Dillenburg', '', '35683', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Dillenburg', '', '35684', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Dillenburg', '', '35685', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Dillenburg', '', '35686', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Dillenburg', '', '35687', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Dillenburg', '', '35688', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Dillenburg', '', '35689', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Dillenburg', '', '35690', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Dipperz', '', '36160', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Dornburg', ' Westerw', '65599', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Dreieich', '', '63303', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Driedorf', '', '35759', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Ebersburg', '', '36157', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Ebsdorfergrund', '', '35085', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Echzell', '', '61209', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Edermünde', '', '34295', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Edertal', '', '34549', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Egelsbach', ' Hess', '63329', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Ehrenberg', '(Rhön)', '36115', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Ehringshausen', ' Dill', '35630', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Eichenzell', '', '36124', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Einhausen', ' Hess', '64683', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Eiserhof', '', '61203', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Eiterfeld', '', '36132', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Elbtal', ' Westerw', '65627', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Eltville', 'am Rhein', '65343', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Eltville', 'am Rhein', '65344', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Eltville', 'am Rhein', '65345', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Eltville', 'am Rhein', '65346', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Eltville', 'am Rhein', '65347', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Elz', ' Westerw', '65604', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Eppertshausen', '', '64859', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Eppstein', ' Taunus', '65817', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Erbach', ' Odenw', '64711', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Erdfunkstelle Usingen', '', '61250', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Erlensee', '', '63526', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Erzhausen', ' Hess', '64390', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Eschborn', ' Taunus', '65760', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Eschenburg', '', '35713', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Eschwege', '', '37269', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Espenau', '', '34314', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Faustenbach', ' Odenw', '64658', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Feldatal', '', '36325', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Felsberg', ' Hess', '34587', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Fernwald', '', '35463', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Fischbachtal', ' Odenw', '64405', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Flieden', '', '36103', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Flörsbachtal', '', '63639', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Flörsheim', 'am Main', '65439', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Florstadt', '', '61197', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Forsthaus Heide', 'b Lampertheim, Hess', '68623', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Frankenau', ' Hess', '35110', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Frankenberg', '(Eder)', '35066', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Frankfurt', 'am Main', '60308', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Frankfurt', 'am Main', '60311', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Frankfurt', 'am Main', '60313', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Frankfurt', 'am Main', '60314', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Frankfurt', 'am Main', '60316', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Frankfurt', 'am Main', '60318', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Frankfurt', 'am Main', '60320', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Frankfurt', 'am Main', '60322', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Frankfurt', 'am Main', '60323', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Frankfurt', 'am Main', '60325', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Frankfurt', 'am Main', '60326', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Frankfurt', 'am Main', '60327', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Frankfurt', 'am Main', '60329', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Frankfurt', 'am Main', '60385', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Frankfurt', 'am Main', '60386', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Frankfurt', 'am Main', '60388', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Frankfurt', 'am Main', '60389', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Frankfurt', 'am Main', '60431', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Frankfurt', 'am Main', '60433', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Frankfurt', 'am Main', '60435', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Frankfurt', 'am Main', '60437', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Frankfurt', 'am Main', '60438', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Frankfurt', 'am Main', '60439', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Frankfurt', 'am Main', '60486', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Frankfurt', 'am Main', '60487', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Frankfurt', 'am Main', '60488', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Frankfurt', 'am Main', '60489', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Frankfurt', 'am Main', '60528', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Frankfurt', 'am Main', '60529', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Frankfurt', 'am Main', '60549', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Frankfurt', 'am Main', '60594', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Frankfurt', 'am Main', '60596', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Frankfurt', 'am Main', '60598', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Frankfurt', 'am Main', '60599', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Frankfurt', 'am Main', '65929', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Frankfurt', 'am Main', '65931', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Frankfurt', 'am Main', '65933', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Frankfurt', 'am Main', '65934', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Frankfurt', 'am Main', '65936', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Fränkisch-Crumbach', '', '64407', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Freiensteinau', '', '36399', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Freigericht', '', '63579', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Friedberg', '(Hessen)', '61169', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Friedewald', ' Hess', '36289', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Friedrichsdorf', ' Taunus', '61381', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Frielendorf', '', '34621', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Fritzlar', '', '34560', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Fronhausen', ' Lahn', '35112', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Fulda', '', '36037', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Fulda', '', '36039', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Fulda', '', '36041', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Fulda', '', '36043', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Fuldabrück', '', '34277', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Fuldatal', '', '34233', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Fürstental', ' Gem Waldeck', '34516', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Fürth', ' Odenw', '64658', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Gebhardshütte', ' Odenw', '64711', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Gedern', '', '63688', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Geisenheim', ' Rheingau', '65366', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Gelnhausen', '', '63571', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Gemünden', '(Wohra)', '35285', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Gemünden', '(Felda)', '35329', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Gernsheim', ' Rhein', '64579', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Gersfeld', '(Rhön)', '36129', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Gestecke', '', '34305', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Gießen', ' Lahn', '35390', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Gießen', ' Lahn', '35392', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Gießen', ' Lahn', '35394', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Gießen', ' Lahn', '35396', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Gießen', ' Lahn', '35398', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Gilserberg', '', '34630', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Ginsheim-Gustavsburg', '', '65462', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Gladenbach', '', '35075', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Glashütten', ' Taunus', '61479', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Glauburg', '', '63695', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Gorxheimertal', '', '69517', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Grasellenbach', '', '64689', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Grävenwiesbach', '', '61279', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Grebenau', ' Hess', '36323', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Grebenhain', '', '36355', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Grebenstein', '', '34393', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Greifenstein', ' Hess', '35753', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Griesheim', ' Hess', '64347', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Griesheim', ' Hess', '64347', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Großalmerode', '', '37247', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Groß-Bieberau', '', '64401', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Großenlüder', '', '36137', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Groß-Gerau', '', '64521', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Großkrotzenburg', '', '63538', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Groß-Rohrheim', '', '68649', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Groß-Umstadt', '', '64823', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Groß-Zimmern', '', '64846', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Grünberg', ' Hess', '35305', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Gründau', '', '63584', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Grundmühle', ' Dill', '35630', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Grünhof', ' Hessen', '34576', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Gudensberg', '', '34281', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Gumpener Kreuz', ' Odenwald', '64385', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Gunkelrode', '', '36179', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Guxhagen', '', '34302', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Habichtswald', '', '34317', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Hadamar', ' Westerw', '65589', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Haiger', '', '35708', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Haina', '(Kloster)', '35114', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Hainburg', ' Hess', '63512', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Hammersbach', ' Hess', '63546', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Hanau', '', '63450', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Hanau', '', '63452', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Hanau', '', '63454', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Hanau', '', '63456', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Hanau', '', '63457', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Hanchesmühle', ' Gem Birstein', '63699', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Hardtmühle', 'b Schwalmtal, Hess', '36304', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Hasenmühle', ' Taunus', '65510', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Hasselroth', '', '63594', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Hattersheim', 'am Main', '65795', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Hatzfeld', '(Eder)', '35116', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Hauneck', '', '36282', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Haunetal', '', '36166', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Heidenrod', '', '65321', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Heinrichsegen', '', '35630', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Helsa', '', '34298', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Heppenheim', '(Bergstraße)', '64646', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Herborn', ' Hess', '35745', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Herborn', ' Hess', '35745', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Herbstein', '', '36358', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Heringen', '(Werra)', '36266', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Herleshausen', '', '37293', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Hesseneck', '', '64754', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Hessisch Lichtenau', '', '37235', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Heuchelheim', ' Kr Gießen', '35452', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Heusenstamm', '', '63150', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Heusenstamm', '', '63150', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Hilders', '', '36115', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Hippelsbach', '', '64395', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Hirschhorn', '(Neckar)', '69434', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Hirzenhain', ' Wetteraukr', '63697', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Hochheim', 'am Main', '65239', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Höchst', 'i Odw', '64739', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Hof Eckeberg', '', '63505', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Hof Mondschirm', ' Gem Ahnatal', '34246', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Hofbieber', '', '36145', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Hofgeismar', '', '34369', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Hofheim', 'am Taunus', '65719', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Hohenahr', '', '35644', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Hohenroda', ' Hess', '36284', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Hohenstein', ' Untertaunus', '65329', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Homberg', '(Efze)', '34576', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Homberg', '(Ohm)', '35315', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Hosenfeld', '', '36154', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Hühnerkirche', '', '65510', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Hundertmorgen', ' Odenwald', '64395', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Hünfeld', '', '36088', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Hünfelden', '', '65597', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Hungen', '', '35410', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Hünstetten', '', '65510', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Hüttelngesäß', '', '63776', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Hüttenberg', ' Hess', '35625', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Idstein', '', '65510', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Igelsbach', 'b Eberbach, Baden', '69412', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Immenhausen', ' Hess', '34376', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Jesberg', '', '34632', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Jossgrund', '', '63637', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Kahler Berg', '', '34225', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Kalbach', ' Rhön', '36148', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Karben', '', '61184', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Kassel', ' Hess', '34117', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Kassel', ' Hess', '34119', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Kassel', ' Hess', '34121', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Kassel', ' Hess', '34123', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Kassel', ' Hess', '34125', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Kassel', ' Hess', '34127', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Kassel', ' Hess', '34128', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Kassel', ' Hess', '34130', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Kassel', ' Hess', '34131', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Kassel', ' Hess', '34132', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Kassel', ' Hess', '34134', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Kassel', ' Hess', '34233', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Kassel', ' Hess', '34355', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Kaufungen', ' Hess', '34260', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Kefenrod', '', '63699', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Kelkheim', '(Taunus)', '65779', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Kelsterbach', '', '65451', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Kiedrich', ' Rheingau', '65399', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Kirchhain', '', '35274', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Kirchheim', ' Hess', '36275', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Kirtorf', '', '36320', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Klippmühle', ' Hess', '34513', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Knüllwald', '', '34593', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Kohlbacher Hof', '', '64395', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Königstein', 'im Taunus', '61462', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Korbach', '', '34497', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Körle', '', '34327', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Kreuzquelle', '', '61209', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Kriftel', '', '65830', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Kronberg', 'im Taunus', '61476', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Künzell', '', '36093', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Lahnau', '', '35633', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Lahntal', '', '35094', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Lampertheim', ' Hess', '68623', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Langen', '(Hessen)', '63225', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Langenselbold', '', '63505', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Langgöns', '', '35428', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Laubach', ' Hess', '35321', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Lauterbach', '(Hessen)', '36341', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Lautertal', '(Vogelsberg)', '36369', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Lautertal', '(Odenwald)', '64686', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Leun', ' Lahn', '35638', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Lich', ' Hess', '35423', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Lichtenfels', ' Hess', '35104', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Liebenau', ' Hess', '34396', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Liederbach', 'am Taunus', '65835', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Limburg', 'a d Lahn', '65549', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Limburg', 'a d Lahn', '65550', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Limburg', 'a d Lahn', '65551', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Limburg', 'a d Lahn', '65552', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Limburg', 'a d Lahn', '65553', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Limburg', 'a d Lahn', '65554', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Limburg', 'a d Lahn', '65555', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Limburg', 'a d Lahn', '65556', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Limeshain', '', '63694', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Linden', ' Hessen', '35440', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Lindenfels', ' Odenw', '64678', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Linsengericht', '', '63589', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Lohfelden', '', '34253', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Löhnberg', '', '35792', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Lohra', '', '35102', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Lollar', '', '35457', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Loosemühle', ' Gem Birstein', '63699', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Lorch', ' Rheingau', '65391', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Lorsch', ' Hess', '64653', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Ludwigsau', ' Hess', '36251', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Lützelbach', ' Odenw', '64750', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Mainhausen', '', '63533', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Maintal', '', '63477', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Mainz-Kastel', '', '55252', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Mainz-Kastel', '', '55252', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Mainz-Kostheim', '', '55246', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Mainz-Kostheim', '', '55246', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Malsfeld', '', '34323', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Marbach', ' Odenwald', '64743', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Marburg', '', '35037', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Marburg', '', '35039', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Marburg', '', '35041', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Marburg', '', '35043', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Meinhard', 'b Eschwege', '37276', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Meißner', 'b Eschwege', '37290', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Melsungen', '', '34212', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Mengerskirchen', '', '35794', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Menglers', '', '36219', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Merenberg', '', '35799', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Messel', '', '64409', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Messel', '', '64409', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Michelbacher Mühle', '', '35094', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Michelbacher Mühle', '', '35094', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Michelstadt', '', '64720', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Mittenaar', '', '35756', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Modautal', '', '64397', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Mörfelden-Walldorf', '', '64546', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Mörlenbach', '', '69509', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Morschen', '', '34326', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Mossautal', '', '64756', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Mücke', '', '35325', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Mühlheim', 'am Main', '63165', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Mühltal', ' Hess', '64367', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Münchhausen', 'am Christenberg', '35117', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Münster', 'b Dieburg', '64839', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Münzenberg', '', '35516', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Nauheim', ' Kr Groß-Gerau', '64569', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Naumburg', ' Hess', '34311', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Neckarsteinach', '', '69239', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Nentershausen', ' Hess', '36214', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Neu-Anspach', '', '61267', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Neuberg', ' Hess', '63543', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Neu-Eichenberg', '', '37249', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Neuenstein', ' Hess', '36286', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Neuental', '', '34599', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Neuhof', ' Kr Fulda', '36119', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Neu-Isenburg', '', '63263', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Neu-Isenburg', '', '63263', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Neukirchen', ' Knüllgeb', '34626', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Neustadt', '(Hessen)', '35279', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Nidda', '', '63667', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Niddatal', '', '61194', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Nidderau', ' Hess', '61130', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Niedenstein', '', '34305', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Niederaula', '', '36272', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Niederdorfelden', '', '61138', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Niedernhausen', ' Taunus', '65527', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Nieste', ' Kr Kassel', '34329', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Niestetal', '', '34266', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Nonnenholz', ' Forsthaus', '37217', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Nonnenholz', ' Forsthaus', '37217', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Nüsttal', '', '36167', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Oberaula', '', '36280', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Ober-Mörlen', '', '61239', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Ober-Ramstadt', '', '64372', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Obertshausen', '', '63179', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Oberursel', '(Taunus)', '61440', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Oberweser', ' Hess', '34399', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Oestrich-Winkel', '', '65375', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Offenbach', 'am Main', '63065', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Offenbach', 'am Main', '63067', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Offenbach', 'am Main', '63069', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Offenbach', 'am Main', '63071', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Offenbach', 'am Main', '63073', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Offenbach', 'am Main', '63075', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Ortenberg', ' Hess', '63683', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Ottrau', '', '34633', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Otzberg', '', '64853', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Petersberg', ' Kr Fulda', '36100', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Pfungstadt', '', '64319', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Philippsthal', '(Werra)', '36269', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Pohlheim', '', '35415', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Poppenhausen', '(Wasserkuppe)', '36163', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Rabenau', ' Hess', '35466', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Ranstadt', '', '63691', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Rasdorf', 'b Hünfeld', '36169', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Raunheim', '', '65479', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Rauschenberg', ' Hess', '35282', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Reichelsheim', '(Wetterau)', '61203', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Reichelsheim', '(Odenwald)', '64385', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Reinhardshagen', '', '34359', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Reinheim', ' Odenw', '64354', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Reiskirchen', ' Wieseck', '35447', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Riedstadt', '', '64560', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Rimbach', ' Odenw', '64668', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Ringgau', '', '37296', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Rockenberg', '', '35519', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Rodenbach', 'b Hanau', '63517', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Rödermark', '', '63322', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Rodgau', '', '63110', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Romrod', '', '36329', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Ronneburg', ' Hess', '63549', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Ronshausen', '', '36217', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Rosbach', 'v d Höhe', '61191', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Rosenthal', ' Hess', '35119', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Roßdorf', 'b Darmstadt', '64380', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Roßdorf', 'b Darmstadt', '64380', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Rotenburg', 'a. d. Fulda', '36199', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Rothenberg', ' Odenw', '64757', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Rüdesheim am Rhein', '', '65385', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Runkel', ' Lahn', '65594', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Rüsselsheim', '', '65428', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Saalburg', ' Taunus, Bahnhof', '61273', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Schaafheim', '', '64850', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Schauenburg', '', '34270', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Schenklengsfeld', '', '36277', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Schimmelshütte', ' Odenw', '64720', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Schlangenbad', ' Taunus', '65388', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Schlitz', '', '36110', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Schlüchtern', '', '36381', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Schmitten', ' Taunus', '61389', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Schöffengrund', '', '35641', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Schöneck', ' Hess', '61137', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Schotten', ' Hess', '63679', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Schrecksbach', '', '34637', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Schwalbach', 'am Taunus', '65824', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Schwalmstadt', '', '34613', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Schwalmtal', ' Hess', '36318', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Schwarzenborn', ' Knüll', '34639', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Seeheim-Jugenheim', '', '64342', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Seligenstadt', ' Hess', '63500', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Selters', '(Taunus)', '65618', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Sennhütte', ' Burghaun', '36166', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Sensbachtal', '', '64759', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Siegbach', '', '35768', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Sinn', ' Hess', '35764', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Sinntal', '', '36391', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Söhrewald', '', '34320', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Solms', ' Lahn', '35606', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Sontra', '', '36205', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Spangenberg', ' Hess', '34286', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Stadtallendorf', '', '35260', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Staufenberg', ' Hess', '35460', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Steffenberg', '', '35239', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Steinau', 'an der Straße', '36396', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Steinbach', '(Taunus)', '61449', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Stockstadt', 'am Rhein', '64589', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Sulzbach', '(Taunus)', '65843', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Tann', '(Rhön)', '36142', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Tannengrundhof', '', '63589', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Taunusstein', '', '65232', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Trebur', '', '65468', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Trendelburg', '', '34388', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Twistetal', '', '34477', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Ulrichstein', '', '35327', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Unter-Hainbrunn', '', '64757', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Usingen', '', '61250', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Vellmar', '', '34246', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Viernheim', '', '68519', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Villmar', '', '65606', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Vöhl', '', '34516', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Volkmarsen', '', '34471', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Wabern', ' Hess', '34590', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Wächtersbach', '', '63607', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Wachtküppel', ' Gem Poppenhausen, Wasserkupp', '36129', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Wahlsburg', ' Weser', '37194', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Waldbrunn', '(Westerwald)', '65620', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Waldeck', ' Hess', '34513', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Waldems', '', '65529', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Waldhaus Grebe', '', '35216', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Waldkappel', '', '37284', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Wald-Michelbach', '', '69483', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Waldsolms', '', '35647', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Walluf', '', '65396', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Wanfried', '', '37281', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Wartenberg', ' Hess', '36367', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Wehretal', '', '37287', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Wehrheim', '', '61273', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Weilburg', '', '35781', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Weilmünster', '', '35789', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Weilrod', '', '61276', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Weimar', '(Lahn)', '35096', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Weinbach', '', '35796', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Weißenborn', 'b Eschwege', '37299', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Weißkirchhof', '', '63589', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Weiterstadt', '', '64331', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Wettenberg', ' Hess', '35435', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Wetter', '(Hessen)', '35083', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Wetzlar', '', '35576', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Wetzlar', '', '35578', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Wetzlar', '', '35579', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Wetzlar', '', '35580', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Wetzlar', '', '35581', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Wetzlar', '', '35582', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Wetzlar', '', '35583', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Wetzlar', '', '35584', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Wetzlar', '', '35585', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Wetzlar', '', '35586', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Wiesbaden', '', '65183', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Wiesbaden', '', '65185', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Wiesbaden', '', '65187', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Wiesbaden', '', '65189', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Wiesbaden', '', '65191', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Wiesbaden', '', '65193', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Wiesbaden', '', '65195', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Wiesbaden', '', '65197', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Wiesbaden', '', '65199', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Wiesbaden', '', '65201', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Wiesbaden', '', '65203', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Wiesbaden', '', '65205', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Wiesbaden', '', '65207', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Wildeck', ' Hess', '36208', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Wildhof', '', '63150', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Willingen', '(Upland)', '34508', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Willingshausen', '', '34628', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Winnerhöfe', ' Hess', '61130', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Winterhof', ' Wetterau', '61203', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Witzenhausen', '', '37213', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Witzenhausen', '', '37214', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Witzenhausen', '', '37215', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Witzenhausen', '', '37216', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Witzenhausen', '', '37217', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Witzenhausen', '', '37218', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Wohratal', '', '35288', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Wölfersheim', '', '61200', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Wolfhagen', '', '34466', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Wöllstadt', '', '61206', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Wünschbach', '', '64753', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Zierenberg', '', '34289', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Zwickmühle', '', '36154', 'HE');
INSERT INTO state_zip_codes (location, location_addition, zip_code, state_id) VALUES ('Zwingenberg', ' Bergstr', '64673', 'HE');
